---
# tasks file for Java_Ansible
- name: Install java
  become: yes
  yum:
    name: java-11-openjdk

- name: Create User java
  become: yes
  ansible.builtin.user:
    name: java_user
    comment: User java
    group: admin
    password: 80e8b5674e908eb2fa4decff4f58f35831d1268d7c2431bfd8e72bc057b41a92

- name: download java app
  become: yes
  get_url:
    url: https://github.com/Ozz007/sb3t/releases/download/1.0/sb3t-ws-1.0.jar
    dest: /home/java_user/

- name: Run Jar
  shell: 'java -jar {{ JAR_PATH }}/{{ JAR_NAME }} -Xmx{{ JVM_SIZE }}'
  become_user : '{{ USER_NAME }}'
  async: 100
 